import type { NextPage } from 'next'
import Head from 'next/head'
import { useSession } from 'next-auth/react'
import Image from 'next/image'
import React from 'react'
import { Product } from '../components'
import { client } from '../db/client'
import { ProductType } from '../utils/types'

const Home: React.FC<{products: ProductType[]}> = ({products}) => {

  return (
    <div className='pb-[500px]'>
      <Head>
        <title>Coral Bids</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className='grid grid-cols-4 items-center'>
          {products.map((product) => (
            <Product key={product.key} product={product} />
          ))}
        </div>
      </div>
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]'
  const products = await client.fetch(query)

  return {
    props: { products }
  }
}

export default Home
