import type { NextPage } from 'next'
import Head from 'next/head'
import { useSession } from 'next-auth/react'
import Image from 'next/image'
import React from 'react'
import { Product } from '../components'
import { client } from '../db/client'

export type ProductsType = [
  {
    _id: string,
    image: string,
    name: string,
    price: number,
    key: string,
    details: string,
    slug: {
      current: string
    }
    openingDate: Date
  }
]

const Home: React.FC<{products: ProductsType}> = ({products}) => {
  const { data: session, status } = useSession()

  console.log(session)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className='grid grid-cols-4 items-center'>
          {products.map((product) => (
            <Product key={product.key} product={product} />
          ))}
        </div>
      </div>
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]'
  const products = await client.fetch(query)

  return {
    props: { products }
  }
}

export default Home
